import { StyleSheet } from 'react-native';
import type { ColorPalette } from '../../context/ThemeContext';
import { fonts } from '../../theme';

export const createTxRowStyles = (colors: ColorPalette, swipeOpen: number) =>
  StyleSheet.create({
    swipeFrame: {
      position: 'relative',
      overflow: 'hidden',
    },
    txRowBorder: {
      borderBottomWidth: 1,
      borderBottomColor: colors.borderSoft,
    },
    swipeActions: {
      ...StyleSheet.absoluteFillObject,
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    swipeAction: {
      width: swipeOpen,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
    },
    editAction: { backgroundColor: colors.moss },
    deleteAction: { backgroundColor: colors.clay },
    disabledAction: { opacity: 0.35 },
    actionLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 11,
      color: colors.paper,
    },
    animatedRow: {
      backgroundColor: colors.cream,
    },
    txRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      paddingVertical: 14,
    },
    txDot: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 4,
    },
    txDotInner: { width: 8, height: 8, borderRadius: 4 },
    txMain: {
      flex: 1,
      minWidth: 0,
      paddingRight: 8,
    },
    txTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    txDescription: {
      flexShrink: 1,
      fontFamily: fonts.display,
      fontSize: 15,
      lineHeight: 19,
      color: colors.ink,
    },
    txMeta: {
      fontFamily: fonts.body,
      fontSize: 11,
      color: colors.stone500,
      marginTop: 2,
      lineHeight: 16,
    },
    txSide: {
      alignItems: 'flex-end',
      minWidth: 96,
    },
    txAmount: {
      fontFamily: fonts.displayLight,
      fontSize: 17,
      textAlign: 'right',
      maxWidth: 116,
    },
    modalRoot: { flex: 1, justifyContent: 'flex-end' },
    modalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: colors.overlay },
    sheet: {
      maxHeight: '86%',
      backgroundColor: colors.cream,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      padding: 24,
      paddingBottom: 36,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      gap: 16,
    },
    sheetHandle: {
      alignSelf: 'center',
      width: 44,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.chip,
      marginTop: -8,
    },
    sheetHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    sheetTitle: {
      fontFamily: fonts.displayLight,
      fontSize: 22,
      color: colors.ink,
    },
    sheetScroll: { gap: 18, paddingBottom: 8 },
    detailHero: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 16,
      backgroundColor: colors.paper,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.borderSoft,
    },
    detailDot: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: 'center',
      justifyContent: 'center',
    },
    detailTitle: {
      fontFamily: fonts.display,
      fontSize: 17,
      color: colors.ink,
      lineHeight: 22,
    },
    detailMeta: {
      fontFamily: fonts.body,
      fontSize: 12,
      color: colors.stone500,
      marginTop: 2,
    },
    detailAmount: {
      fontFamily: fonts.displayLight,
      fontSize: 18,
      textAlign: 'right',
    },
    detailGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    detailItem: {
      width: '48%',
      padding: 12,
      borderRadius: 12,
      backgroundColor: colors.paper,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      gap: 4,
    },
    detailLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 10,
      textTransform: 'uppercase',
      letterSpacing: 1,
      color: colors.stone500,
    },
    detailValue: {
      fontFamily: fonts.bodyMedium,
      fontSize: 13,
      color: colors.ink,
      textTransform: 'capitalize',
    },
    primaryAction: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 13,
      borderRadius: 999,
      backgroundColor: colors.ink,
    },
    primaryActionLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 14,
      color: colors.paper,
    },
    auditSection: { gap: 12 },
    auditHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'baseline',
    },
    auditTitle: {
      fontFamily: fonts.displayLight,
      fontSize: 22,
      color: colors.ink,
    },
    auditCount: {
      fontFamily: fonts.bodyMedium,
      fontSize: 10,
      letterSpacing: 1.2,
      textTransform: 'uppercase',
      color: colors.stone500,
    },
    auditEmpty: {
      padding: 18,
      borderRadius: 14,
      backgroundColor: colors.paper,
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: colors.borderSoft,
    },
    auditEmptyText: {
      fontFamily: fonts.displayItalic,
      fontSize: 13,
      color: colors.stone500,
      textAlign: 'center',
    },
    auditCard: {
      padding: 14,
      borderRadius: 14,
      backgroundColor: colors.paper,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      gap: 4,
    },
    auditDate: {
      fontFamily: fonts.bodyMedium,
      fontSize: 11,
      color: colors.stone500,
    },
    auditBody: {
      fontFamily: fonts.body,
      fontSize: 13,
      color: colors.ink,
      lineHeight: 18,
    },
    auditDelta: {
      fontFamily: fonts.body,
      fontSize: 11,
      color: colors.stone500,
    },
  });
