import { StyleSheet } from 'react-native';
import type { ColorPalette } from '../../context/ThemeContext';
import { fonts } from '../../theme';

export const createDashboardStyles = (colors: ColorPalette) =>
  StyleSheet.create({
    ledgerPanel: {
      backgroundColor: colors.cream,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      padding: 18,
      gap: 18,
    },
    ledgerPanelHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    ledgerTitleGroup: {
      flex: 1,
      minWidth: 0,
    },
    ledgerEyebrow: {
      fontFamily: fonts.bodyMedium,
      fontSize: 10,
      letterSpacing: 1.4,
      textTransform: 'uppercase',
      color: colors.stone500,
    },
    ledgerTitle: {
      fontFamily: fonts.displayLight,
      fontSize: 28,
      color: colors.ink,
      marginTop: 2,
    },
    ledgerAccountMeta: {
      fontFamily: fonts.body,
      fontSize: 12,
      color: colors.stone500,
      marginTop: 3,
    },
    ledgerIcon: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: colors.chip,
      alignItems: 'center',
      justifyContent: 'center',
    },
    ledgerBalanceRow: {
      gap: 16,
    },
    ledgerMetricLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 10,
      letterSpacing: 1.2,
      textTransform: 'uppercase',
      color: colors.stone500,
      marginBottom: 4,
    },
    ledgerBalance: {
      fontFamily: fonts.displayLight,
      fontSize: 34,
    },
    ledgerPair: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 16,
    },
    ledgerMetric: {
      fontFamily: fonts.displayLight,
      fontSize: 20,
    },
    ledgerChips: {
      gap: 8,
      paddingRight: 8,
    },
    ledgerChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.chip,
    },
    ledgerChipDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
    },
    ledgerChipLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      color: colors.inkSoft,
    },
    addLedgerChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.paper,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      borderStyle: 'dashed',
    },
    addLedgerLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      color: colors.rust,
    },
    archivedChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.chip,
    },
    archivedChipLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      color: colors.stone500,
    },
    archivedRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 14,
      paddingVertical: 14,
      borderRadius: 14,
      backgroundColor: colors.paper,
      borderWidth: 1,
      borderColor: colors.borderSoft,
    },
    archivedRowName: {
      fontFamily: fonts.displayLight,
      fontSize: 16,
      color: colors.ink,
    },
    archivedRowMeta: {
      fontFamily: fonts.body,
      fontSize: 11,
      color: colors.stone500,
      marginTop: 2,
    },
    archivedEmpty: {
      fontFamily: fonts.body,
      fontSize: 13,
      color: colors.stone500,
      textAlign: 'center',
      paddingVertical: 16,
    },
    budgetEmpty: {
      backgroundColor: colors.cream,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      borderStyle: 'dashed',
      padding: 18,
      gap: 6,
      alignItems: 'flex-start',
    },
    budgetEmptyTitle: {
      fontFamily: fonts.displayLight,
      fontSize: 18,
      color: colors.ink,
      marginTop: 4,
    },
    budgetEmptyCopy: {
      fontFamily: fonts.body,
      fontSize: 12,
      color: colors.stone500,
    },
    budgetAddRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 14,
      backgroundColor: colors.paper,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      borderStyle: 'dashed',
      alignSelf: 'flex-start',
    },
    budgetAddLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      color: colors.rust,
    },
    budgetCard: {
      backgroundColor: colors.cream,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      padding: 14,
      gap: 10,
    },
    budgetCardHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    budgetCardTitleGroup: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexWrap: 'wrap',
    },
    budgetCategoryDot: {
      width: 9,
      height: 9,
      borderRadius: 5,
    },
    budgetCardTitle: {
      fontFamily: fonts.displayMedium,
      fontSize: 16,
      color: colors.ink,
    },
    budgetLedgerPill: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 999,
      borderWidth: 1,
    },
    budgetLedgerPillLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 10,
      letterSpacing: 0.6,
      color: colors.stone600,
    },
    budgetStatusLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      letterSpacing: 0.5,
    },
    budgetBarTrack: {
      height: 6,
      borderRadius: 999,
      backgroundColor: colors.chip,
      overflow: 'hidden',
    },
    budgetBarFill: {
      height: '100%',
      borderRadius: 999,
    },
    budgetMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    budgetMetaPrimary: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      color: colors.ink,
    },
    budgetMetaSecondary: {
      fontFamily: fonts.body,
      fontSize: 11,
    },
    budgetWarning: {
      fontFamily: fonts.body,
      fontSize: 11,
      color: colors.stone500,
      fontStyle: 'italic',
    },
    goalEmpty: {
      backgroundColor: colors.cream,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      borderStyle: 'dashed',
      padding: 18,
      gap: 6,
      alignItems: 'flex-start',
    },
    goalCard: {
      backgroundColor: colors.cream,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      padding: 14,
      gap: 10,
    },
    goalHead: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
    },
    goalTitle: {
      fontFamily: fonts.displayMedium,
      fontSize: 17,
      color: colors.ink,
      lineHeight: 22,
    },
    goalMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 6,
    },
    goalStatusPill: {
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 2,
    },
    goalStatusLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 10,
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    goalLedgerText: {
      flexShrink: 1,
      fontFamily: fonts.body,
      fontSize: 11,
      color: colors.stone500,
    },
    goalPercent: {
      fontFamily: fonts.displayLight,
      fontSize: 22,
    },
    goalAmountRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    goalDetailRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 8,
      flexWrap: 'wrap',
    },
    goalDetailText: {
      fontFamily: fonts.body,
      fontSize: 11,
      color: colors.stone500,
    },
    goalCompleteButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 11,
      borderRadius: 999,
      backgroundColor: colors.rust,
      marginTop: 2,
    },
    goalCompleteButtonLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      color: colors.paper,
    },
    completedGoalsFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      gap: 6,
      marginTop: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.chip,
    },
    completedGoalsFooterLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      color: colors.stone500,
    },
    completedGoalRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 14,
      paddingVertical: 14,
      borderRadius: 14,
      backgroundColor: colors.paper,
      borderWidth: 1,
      borderColor: colors.borderSoft,
    },
    card: {
      backgroundColor: colors.cream,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      padding: 16,
    },
    legendWrapper: {
      flexDirection: 'row',
      gap: 18,
      justifyContent: 'center',
      marginTop: 8,
    },
    entryTabs: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginBottom: 12,
      padding: 4,
      backgroundColor: colors.chip,
      borderRadius: 999,
      alignSelf: 'flex-start',
    },
    entryTab: {
      paddingHorizontal: 16,
      paddingVertical: 7,
      borderRadius: 999,
    },
    entryTabLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
    },
    list: {
      backgroundColor: colors.cream,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      paddingHorizontal: 14,
    },
    modalRoot: { flex: 1, justifyContent: 'flex-end' },
    modalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: colors.overlay },
    sheet: {
      backgroundColor: colors.cream,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      padding: 24,
      paddingBottom: 32,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      gap: 18,
    },
    sheetHandle: {
      alignSelf: 'center',
      width: 44,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.chip,
      marginTop: -8,
    },
    sheetHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    sheetTitle: {
      fontFamily: fonts.displayLight,
      fontSize: 22,
      color: colors.ink,
    },
  });
