import { StyleSheet } from 'react-native';
import type { ColorPalette } from '../../context/ThemeContext';
import { fonts } from '../../theme';

export const createConfirmOccurrenceStyles = (colors: ColorPalette) =>
  StyleSheet.create({
    modalRoot: { flex: 1, justifyContent: 'flex-end' },
    modalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: colors.overlay },
    sheet: {
      backgroundColor: colors.cream,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      padding: 24,
      paddingBottom: 32,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      gap: 18,
      maxHeight: '92%',
    },
    sheetHandle: {
      alignSelf: 'center',
      width: 44,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.chip,
      marginTop: -8,
    },
    sheetHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    sheetTitle: {
      fontFamily: fonts.displayLight,
      fontSize: 22,
      color: colors.ink,
    },
    sourceTitle: {
      fontFamily: fonts.displayMedium,
      fontSize: 17,
      color: colors.ink,
    },
    amountRow: { flexDirection: 'row', alignItems: 'baseline', gap: 8 },
    amountSign: { fontFamily: fonts.displayLight, fontSize: 28, color: colors.stone400 },
    amountInput: {
      flex: 1,
      fontFamily: fonts.displayLight,
      fontSize: 28,
      color: colors.ink,
      paddingVertical: 4,
    },
    input: {
      fontFamily: fonts.body,
      fontSize: 15,
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderSoft,
      color: colors.ink,
    },
    dateButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderSoft,
    },
    dateButtonText: {
      fontFamily: fonts.body,
      fontSize: 15,
      color: colors.ink,
    },
    chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    chip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.chip,
    },
    chipDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
    },
    chipLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      color: colors.inkSoft,
    },
    proofGrid: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 10,
    },
    proofButton: {
      flex: 1,
      minHeight: 48,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      backgroundColor: colors.paper,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 6,
    },
    proofButtonText: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      color: colors.ink,
    },
    proofModeRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 10,
    },
    proofMode: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 11,
      paddingVertical: 7,
      borderRadius: 999,
      backgroundColor: colors.chip,
    },
    proofModeText: {
      fontFamily: fonts.bodyMedium,
      fontSize: 11,
      color: colors.stone600,
    },
    proofTextArea: {
      minHeight: 76,
      textAlignVertical: 'top',
      fontFamily: fonts.body,
      fontSize: 14,
      color: colors.ink,
      backgroundColor: colors.paper,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    proofInline: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 10,
    },
    detectedPanel: {
      marginTop: 10,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      backgroundColor: colors.paper,
      padding: 10,
      gap: 8,
    },
    detectedTitle: {
      fontFamily: fonts.bodyMedium,
      fontSize: 11,
      color: colors.stone500,
      textTransform: 'uppercase',
      letterSpacing: 0.7,
    },
    detectedChips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 7,
    },
    detectedChip: {
      fontFamily: fonts.bodyMedium,
      fontSize: 11,
      color: colors.rust,
      backgroundColor: colors.chip,
      borderRadius: 999,
      paddingHorizontal: 9,
      paddingVertical: 4,
    },
    proofInput: {
      flex: 1,
      minWidth: 0,
      fontFamily: fonts.body,
      fontSize: 14,
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderSoft,
      color: colors.ink,
    },
    proofAdd: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      minWidth: 92,
      borderRadius: 999,
      backgroundColor: colors.ink,
      paddingHorizontal: 12,
    },
    proofAddText: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      color: colors.paper,
    },
    proofList: {
      gap: 8,
      marginTop: 10,
    },
    proofItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
      padding: 9,
      borderRadius: 13,
      backgroundColor: colors.paper,
      borderWidth: 1,
      borderColor: colors.borderSoft,
    },
    proofThumb: {
      width: 34,
      height: 34,
      borderRadius: 9,
      backgroundColor: colors.chip,
    },
    proofIcon: {
      width: 34,
      height: 34,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.chip,
    },
    proofSummary: {
      flex: 1,
      minWidth: 0,
      fontFamily: fonts.body,
      fontSize: 12,
      color: colors.stone600,
    },
    submit: {
      backgroundColor: colors.ink,
      paddingVertical: 14,
      borderRadius: 999,
      alignItems: 'center',
    },
    submitLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 14,
      color: colors.paper,
      letterSpacing: 0.5,
    },
  });
