import { StyleSheet } from 'react-native';
import type { ColorPalette } from '../../context/ThemeContext';
import { fonts } from '../../theme';

export const createBillsStyles = (colors: ColorPalette) =>
  StyleSheet.create({
    hero: {
      backgroundColor: colors.ink,
      borderRadius: 22,
      padding: 22,
      gap: 22,
    },
    heroHead: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 16,
    },
    heroEyebrow: {
      fontFamily: fonts.bodyMedium,
      fontSize: 10,
      letterSpacing: 1.5,
      textTransform: 'uppercase',
      color: colors.paper,
      opacity: 0.65,
    },
    heroTitle: {
      fontFamily: fonts.displayLight,
      fontSize: 34,
      color: colors.paper,
      marginTop: 4,
    },
    heroIcon: {
      width: 46,
      height: 46,
      borderRadius: 23,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.paper,
    },
    heroMetrics: {
      flexDirection: 'row',
      gap: 10,
    },
    metric: {
      flex: 1,
      minWidth: 0,
      padding: 12,
      borderRadius: 14,
      backgroundColor: 'rgba(255,255,255,0.08)',
    },
    metricLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 10,
      letterSpacing: 1,
      textTransform: 'uppercase',
      color: colors.paper,
      opacity: 0.58,
    },
    metricValue: {
      fontFamily: fonts.displayLight,
      fontSize: 23,
      color: colors.paper,
      marginTop: 3,
    },
    reminderCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.cream,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      padding: 14,
    },
    reminderCopy: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    reminderIcon: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.paper,
      alignItems: 'center',
      justifyContent: 'center',
    },
    reminderTitle: {
      fontFamily: fonts.displayMedium,
      fontSize: 16,
      color: colors.ink,
    },
    reminderMeta: {
      fontFamily: fonts.body,
      fontSize: 11,
      color: colors.stone500,
      marginTop: 2,
    },
    syncNote: {
      fontFamily: fonts.body,
      fontSize: 11,
      color: colors.rust,
      marginTop: 4,
    },
    reminderButton: {
      minWidth: 76,
      minHeight: 40,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 14,
      backgroundColor: colors.rust,
    },
    reminderButtonLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      color: colors.paper,
    },
    tabs: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 12,
    },
    tab: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.chip,
    },
    tabLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      color: colors.inkSoft,
    },
    tabCount: {
      fontFamily: fonts.bodyMedium,
      fontSize: 11,
      color: colors.stone500,
    },
    occurrenceCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      backgroundColor: colors.cream,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      padding: 14,
    },
    datePill: {
      width: 50,
      borderRadius: 12,
      backgroundColor: colors.paper,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      alignItems: 'center',
      paddingVertical: 8,
    },
    dateMonth: {
      fontFamily: fonts.bodyMedium,
      fontSize: 10,
      color: colors.stone500,
      textTransform: 'uppercase',
      letterSpacing: 1,
    },
    dateDay: {
      fontFamily: fonts.displayLight,
      fontSize: 20,
      color: colors.ink,
      marginTop: 2,
    },
    occurrenceHead: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
    },
    occurrenceTitle: {
      fontFamily: fonts.displayMedium,
      fontSize: 16,
      color: colors.ink,
      lineHeight: 21,
    },
    occurrenceMeta: {
      fontFamily: fonts.body,
      fontSize: 11,
      color: colors.stone500,
      lineHeight: 16,
      marginTop: 2,
    },
    occurrenceAmount: {
      fontFamily: fonts.displayLight,
      fontSize: 17,
      textAlign: 'right',
      maxWidth: 110,
    },
    statusRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexWrap: 'wrap',
    },
    statusPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    statusLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 10,
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    dueText: {
      fontFamily: fonts.body,
      fontSize: 11,
      color: colors.stone500,
    },
    proofPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      borderRadius: 12,
      paddingHorizontal: 8,
      paddingVertical: 6,
      backgroundColor: colors.chip,
      maxWidth: '100%',
      flexShrink: 1,
    },
    proofIconWrap: {
      width: 22,
      height: 22,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
    },
    proofThumb: {
      width: 26,
      height: 26,
      borderRadius: 6,
      backgroundColor: colors.chip,
    },
    proofLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 11,
      letterSpacing: 0.2,
    },
    proofMeta: {
      fontFamily: fonts.body,
      fontSize: 10,
      color: colors.stone500,
      marginTop: 1,
    },
    warningText: {
      fontFamily: fonts.body,
      fontSize: 11,
      color: colors.clay,
      fontStyle: 'italic',
    },
    actions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexWrap: 'wrap',
    },
    actionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 11,
      paddingVertical: 7,
      borderRadius: 999,
    },
    actionLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 11,
      color: colors.paper,
    },
    secondaryAction: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 11,
      paddingVertical: 7,
      borderRadius: 999,
      backgroundColor: colors.chip,
    },
    secondaryActionLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 11,
      color: colors.stone600,
    },
  });
