import { StyleSheet } from 'react-native';
import type { ColorPalette } from '../../context/ThemeContext';
import { fonts } from '../../theme';

export const createSettingsStyles = (colors: ColorPalette) =>
  StyleSheet.create({
    container: { gap: 24 },
    headerTitle: {
      fontFamily: fonts.displayLight,
      fontSize: 32,
      color: colors.ink,
      marginBottom: 8,
    },
    card: {
      backgroundColor: colors.cream,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      overflow: 'hidden',
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 16,
    },
    currencyRow: {
      padding: 16,
      gap: 12,
    },
    rowLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    rowLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 15,
      color: colors.ink,
    },
    divider: {
      height: 1,
      backgroundColor: colors.borderSoft,
      marginHorizontal: 16,
    },
    reminderBlock: {
      paddingBottom: 12,
    },
    reminderMeta: {
      fontFamily: fonts.body,
      fontSize: 11,
      color: colors.stone500,
      marginTop: 2,
    },
    reminderSyncBtn: {
      alignSelf: 'flex-start',
      marginLeft: 48,
      marginRight: 16,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.chip,
    },
    reminderSyncLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      color: colors.rust,
    },
    reminderNote: {
      fontFamily: fonts.body,
      fontSize: 11,
      color: colors.stone500,
      paddingHorizontal: 16,
      marginTop: 6,
    },
    appearanceRow: {
      padding: 16,
      gap: 12,
    },
    modeToggle: {
      flexDirection: 'row',
      backgroundColor: colors.chip,
      borderRadius: 999,
      padding: 4,
      gap: 4,
    },
    modeBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 8,
      borderRadius: 999,
    },
    modeBtnLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      letterSpacing: 0.3,
    },
    themeBlock: {
      padding: 16,
      gap: 12,
    },
    presetGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    presetCard: {
      width: '48%',
      flexGrow: 1,
      padding: 12,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      backgroundColor: colors.paper,
      gap: 8,
    },
    presetSwatchRow: {
      flexDirection: 'row',
      gap: 4,
      height: 18,
      borderRadius: 4,
      overflow: 'hidden',
    },
    presetSwatch: {
      flex: 1,
      borderRadius: 4,
    },
    presetCardHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    presetName: {
      fontFamily: fonts.displayMedium,
      fontSize: 14,
      color: colors.ink,
    },
    presetDescription: {
      fontFamily: fonts.body,
      fontSize: 11,
      color: colors.stone500,
      lineHeight: 15,
    },
    swatchGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      alignItems: 'center',
    },
    accentSwatch: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    accentSwatchActive: {
      borderWidth: 2,
      borderColor: colors.ink,
    },
    accentSwatchAuto: {
      paddingHorizontal: 12,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.chip,
      borderWidth: 1,
      borderColor: colors.borderSoft,
    },
    accentSwatchAutoLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 11,
      color: colors.inkSoft,
    },
    themeHint: {
      fontFamily: fonts.body,
      fontSize: 11,
      color: colors.stone500,
      lineHeight: 15,
    },
    fontRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 14,
      paddingVertical: 14,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      backgroundColor: colors.paper,
    },
    fontPreviewDisplay: {
      fontSize: 18,
      color: colors.ink,
    },
    fontPreviewBody: {
      fontSize: 12,
      color: colors.stone500,
      marginTop: 2,
    },
    currencyToggle: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      backgroundColor: colors.chip,
      padding: 6,
      borderRadius: 12,
      alignSelf: 'stretch',
    },
    currencyBtn: {
      flexGrow: 1,
      flexBasis: '30%',
      alignItems: 'center',
      paddingHorizontal: 10,
      paddingVertical: 10,
      borderRadius: 8,
    },
    currencyBtnText: {
      fontFamily: fonts.bodyMedium,
      fontSize: 14,
      color: colors.inkSoft,
    },
    sectionHeader: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      letterSpacing: 1.2,
      textTransform: 'uppercase',
      color: colors.stone500,
      marginTop: 8,
    },
    aboutRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
      paddingHorizontal: 16,
      gap: 12,
    },
    aboutMeta: {
      fontFamily: fonts.body,
      fontSize: 11,
      color: colors.stone500,
      marginTop: 2,
    },
    dangerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 16,
    },
    dangerLabel: {
      fontFamily: fonts.bodyMedium,
      fontSize: 15,
      color: colors.clay,
    },
    dangerDesc: {
      fontFamily: fonts.body,
      fontSize: 12,
      color: colors.stone500,
      paddingHorizontal: 16,
      paddingBottom: 16,
      marginTop: -8,
      lineHeight: 18,
    },
  });
